# Generated by Django 3.2.23 on 2024-01-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="staticfiles/img/news"
            ),
        ),
    ]
