# Generated by Django 3.2.23 on 2024-01-10 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_pig_breeder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pig',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PIG_owner', to='main_page.breeding'),
        ),
    ]
