# Generated by Django 3.2.23 on 2024-01-12 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_pig_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pig',
            name='owner',
        ),
        migrations.AddField(
            model_name='pig',
            name='owner',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='PIG_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
