# Generated by Django 3.2.23 on 2024-01-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pig',
            name='breeder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
