# Generated by Django 3.2.23 on 2023-11-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='club',
            field=models.CharField(blank=True, choices=[('PL', 'Polska (CCP)'), ('SOCHM', 'Czech Republic (SOCHM)'), ('SZOCHVM', 'Czech Republic (SZOCHVM)'), ('SK', 'Slovakia'), ('UA', 'Ukraine'), ('SE', 'Sweden'), ('DMK', 'Denmark (DMK)'), ('DMF', 'Denmark (DMF)'), ('FI', 'Finland'), ('NMK', 'Norway (NMK)'), ('NMF', 'Norway (NMF)'), ('GB', 'Great Britain'), ('MFD', 'Germany (MFD)'), ('OMNC', 'Germany (OMNC)'), ('NL', 'Netherlands'), ('FAEC', 'France (FAEC)'), ('CCF', 'France (CCF)'), ('CH', 'Switzerland'), ('BE', 'Belgium'), ('AT', 'Austria'), ('IT', 'Italy'), ('ES', 'Spain'), ('PT', 'Portugal'), ('IE', 'Ireland'), ('SI', 'Slovenia'), ('HU', 'Hungary'), ('USA', 'USA'), ('CA', 'Canada'), ('AU', 'Australia'), ('NZ', 'New Zealand')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('PL', 'Polska'), ('CZ', 'Czech Republic'), ('SK', 'Slovakia'), ('UA', 'Ukraine'), ('SE', 'Sweden'), ('DK', 'Denmark'), ('FI', 'Finland'), ('NO', 'Norway'), ('GB', 'Great Britain'), ('DE', 'Germany'), ('NL', 'Netherlands'), ('FR', 'France'), ('CH', 'Switzerland'), ('BE', 'Belgium'), ('AT', 'Austria'), ('IT', 'Italy'), ('ES', 'Spain'), ('PT', 'Portugal'), ('IE', 'Ireland'), ('SI', 'Slovenia'), ('HU', 'Hungary'), ('USA', 'USA'), ('CA', 'Canada'), ('AU', 'Australia'), ('NZ', 'New Zealand')], max_length=20),
        ),
    ]
